/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.feitian;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.bluetooth.BluetoothDevice;

@Kroll.proxy(creatableInModule = FeitianModule.class)
public class DeviceProxy extends KrollProxy {
	// Standard Debugging variables
	private static final String LCAT = "ExampleProxy";
	private static final boolean DBG = TiConfig.LOGD;
	private BluetoothDevice device;

	public DeviceProxy() {
		super();
	}
	
	public DeviceProxy(BluetoothDevice device) {
		super();
		this.device=device;
	}
	
	@Kroll.method
	public String getName() {
		return device.getName();
	}
	@Kroll.method
	public String getAddress() {
		return device.getAddress();
	}
	@Kroll.method
	public void readData() {
				
	}
	
}
