/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.feitian;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;

import com.feitian.readerdk.Tool.DK;

import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothSocket;
import android.content.Context;
import android.os.Handler;
import android.os.Message;

import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name = "Feitiansmartcardreader", id = "de.appwerft.feitian")
public class FeitiansmartcardreaderModule extends KrollModule {

	// Standard Debugging variables
	public static final String LCAT = "FeitianModule";
	
	
	ArrayList<String> list;
	ArrayList<BluetoothDevice> arrayForBlueToothDevice;
	//
	private List<String> list2 = new ArrayList<String>();
	private List<String> list3 = new ArrayList<String>();

	private static final UUID MY_UUID = UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");
	// for test
	private BluetoothDevice blueToothDevice;

	private BluetoothSocket blueToothSocket;
	private InputStream input;
	private OutputStream output;
	private BluetoothAdapter bluetoothAdapter;
	private int testi = 0;
	private Context ctx = TiApplication.getInstance().getApplicationContext();
	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public FeitiansmartcardreaderModule() {
		super();
		bluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {

	}
	
	private final Handler handler = new Handler() {
		@Override
		public void handleMessage(Message msg) {
			switch (msg.what) {
			case DK.CARD_STATUS:
				switch (msg.arg1) {
				case DK.CARD_ABSENT:
					displayData("IFD", "card absent");
				//	stat_poweroff();
					break;
				case DK.CARD_PRESENT:
					displayData("IFD", "card persent");
					// try {
					// mReader.PowerOff();
					// mReader.PowerOn();
					// } catch (FtBlueReadException e) {
					// // TODO Auto-generated catch block
					// e.printStackTrace();
					// }
					break;
				case DK.CARD_UNKNOWN:
					displayData("IFD", "card unknown");
					break;
				case DK.IFD_COMMUNICATION_ERROR:
					displayData("IFD", "IFD error");
					break;
				}
			default:
				break;
			}
		}
};

}
